/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      // Touch-Targets ≥ 44px (siehe MILESTONES.md, M5).
      minHeight: {
        touch: '2.75rem',
      },
      minWidth: {
        touch: '2.75rem',
      },
      colors: {
        // Brand Core
        'korps-rot':       'var(--korps-rot)',
        'korps-rot-tief':  'var(--korps-rot-tief)',
        'korps-rot-licht': 'var(--korps-rot-licht)',
        'kupfer':          'var(--kupfer)',
        'kupfer-tief':     'var(--kupfer-tief)',
        'kupfer-licht':    'var(--kupfer-licht)',
        'pergament':       'var(--pergament)',
        'pergament-tief':  'var(--pergament-tief)',
        'tinte':           'var(--tinte)',
        'tinte-2':         'var(--tinte-2)',
        'tinte-3':         'var(--tinte-3)',
        'tinte-4':         'var(--tinte-4)',
        'kreide':          'var(--kreide)',
        'schaum':          'var(--schaum)',
        'eiche':           'var(--eiche)',
        'eiche-2':         'var(--eiche-2)',
        'messing':         'var(--messing)',
        // Semantic
        'bg':              'var(--bg)',
        'bg-2':            'var(--bg-2)',
        'bg-card':         'var(--bg-card)',
        'bg-card-hover':   'var(--bg-card-hover)',
        'brand':           'var(--brand)',
        'accent':          'var(--accent)',
        'gold':            'var(--gold)',
        'line':            'var(--line)',
        'line-2':          'var(--line-2)',
        // Status
        'erfolg':          'var(--erfolg)',
        'erfolg-bg':       'var(--erfolg-bg)',
        'warnung':         'var(--warnung)',
        'warnung-bg':      'var(--warnung-bg)',
        'fehler':          'var(--fehler)',
        'fehler-bg':       'var(--fehler-bg)',
        'info':            'var(--info)',
        'info-bg':         'var(--info-bg)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        serif:   'var(--font-serif)',
        sans:    'var(--font-sans)',
        hand:    'var(--font-hand)',
        mono:    'var(--font-mono)',
      },
      fontSize: {
        '12': ['var(--fs-12)', { lineHeight: '1.4' }],
        '14': ['var(--fs-14)', { lineHeight: '1.45' }],
        '16': ['var(--fs-16)', { lineHeight: '1.55' }],
        '18': ['var(--fs-18)', { lineHeight: '1.5' }],
        '20': ['var(--fs-20)', { lineHeight: '1.4' }],
        '24': ['var(--fs-24)', { lineHeight: '1.3' }],
        '32': ['var(--fs-32)', { lineHeight: '1.2' }],
        '44': ['var(--fs-44)', { lineHeight: '1.1' }],
        '60': ['var(--fs-60)', { lineHeight: '1.05' }],
        '84': ['var(--fs-84)', { lineHeight: '1' }],
      },
      spacing: {
        's-1': 'var(--s-1)',
        's-2': 'var(--s-2)',
        's-3': 'var(--s-3)',
        's-4': 'var(--s-4)',
        's-5': 'var(--s-5)',
        's-6': 'var(--s-6)',
        's-7': 'var(--s-7)',
        's-8': 'var(--s-8)',
        's-9': 'var(--s-9)',
      },
      borderRadius: {
        '0':    'var(--r-0)',
        '1':    'var(--r-1)',
        '2':    'var(--r-2)',
        '3':    'var(--r-3)',
        'pill': 'var(--r-pill)',
      },
      boxShadow: {
        'sh-1':     'var(--sh-1)',
        'sh-2':     'var(--sh-2)',
        'sh-3':     'var(--sh-3)',
        'sh-inset': 'var(--sh-inset)',
        'emboss':   'var(--sh-emboss)',
      },
      transitionTimingFunction: {
        'stempel':  'cubic-bezier(.2,.8,.2,1)',
        'out-soft': 'cubic-bezier(0,0,.2,1)',
      },
      transitionDuration: {
        'fast': 'var(--dur-fast)',
        'base': 'var(--dur-base)',
        'slow': 'var(--dur-slow)',
      },
    },
  },
  plugins: [],
};
